#!/usr/bin/env sh
# Regenerates docs/agents-catalog.md from the frontmatter of agents/*.md.
# Run from the repository root:  sh scripts/docs/agents-catalog.sh
# CI compares the output to the committed file, so commit both together.
set -eu

out="docs/agents-catalog.md"
tmp="$(mktemp)"
trap 'rm -f "$tmp"' EXIT

group_title() {
  case "$1" in
    aws) echo "AWS" ;;
    azure) echo "Azure" ;;
    gcp) echo "GCP" ;;
    github) echo "GitHub" ;;
    k8s) echo "Kubernetes" ;;
    *) echo "$1" ;;
  esac
}

description() {
  # First "description:" key in the frontmatter, value only.
  sed -n '/^description:/{s/^description:[[:space:]]*//;p;q;}' "$1"
}

# Number of arguments; called with a glob so the shell, not ls, does the counting.
count() {
  echo "$#"
}

bt='`'
total=$(count agents/*.md)

{
  echo "# Built-in agent catalog"
  echo
  echo "<!-- Generated by scripts/docs/agents-catalog.sh from agents/*.md. Do not edit by hand. -->"
  echo
  echo "Cynative ships with $total built-in agents. Run one with"
  echo "${bt}cynative -p --agent <name>${bt}, print it with ${bt}cynative agents show <name>${bt},"
  echo "and see [agents.md](agents.md) for how to write your own."
  echo

  prev=""
  for f in agents/*.md; do
    name=$(basename "$f" .md)
    group=${name%%-*}
    if [ "$group" != "$prev" ]; then
      [ -n "$prev" ] && echo
      n=$(count agents/"$group"-*.md)
      echo "## $(group_title "$group") ($n)"
      echo
      echo "| Agent | What it answers |"
      echo "|---|---|"
      prev=$group
    fi
    printf '| %s%s%s | %s |\n' "$bt" "$name" "$bt" "$(description "$f")"
  done
} > "$tmp"

mv "$tmp" "$out"
echo "wrote $out ($total agents)"
