#!/usr/bin/env sh
# Regenerates docs/agents-catalog.md from the frontmatter of agents/*.md.
# Run from the repository root:  sh scripts/docs/agents-catalog.sh
# Pass --check to render from the index (the agent files and the catalog as they
# are staged, which in CI is the commit under test) and compare the two, writing
# nothing; that is how the gate fails a stale catalog. Exit 1 means stale or not
# tracked, exit 2 means bad usage. With no argument it rewrites the working tree
# file. Commit the agent change and the regenerated catalog together.
set -eu

out="docs/agents-catalog.md"
mode="write"
if [ "${1:-}" = "--check" ]; then
  mode="check"
elif [ "$#" -gt 0 ]; then
  echo "usage: $(basename "$0") [--check]" >&2
  exit 2
fi

tmp="$(mktemp)"
trap 'rm -f "$tmp"' EXIT

if [ "$mode" = "check" ]; then
  # Both sides of the comparison are raw index blobs, so they describe the same
  # thing: the agents and the catalog exactly as staged. A working-tree copy an
  # earlier generate step rewrote never enters it, a partially staged edit can
  # neither fail the check spuriously nor slip a stale catalog past it, and no
  # end-of-line or smudge conversion touches either side, which checkout-index
  # would apply. quotePath is off so a non-ASCII name reaches cat-file as the
  # bytes the index holds rather than C-quoted.
  stage="$(mktemp -d)"
  trap 'rm -rf "$tmp" "$stage"' EXIT
  git -c core.quotePath=false ls-files -- agents "$out" | while IFS= read -r path; do
    mkdir -p "$stage/$(dirname "$path")"
    git cat-file blob ":$path" > "$stage/$path"
  done
  if [ ! -d "$stage/agents" ]; then
    echo "error: no agents/ entries in the index; run from the repository root" >&2
    exit 1
  fi
  if [ ! -f "$stage/$out" ]; then
    echo "error: $out is not in the index; run 'make generate' and git add it" >&2
    exit 1
  fi
  cd "$stage" || exit 1
fi

group_title() {
  case "$1" in
    aws) echo "AWS" ;;
    azure) echo "Azure" ;;
    gcp) echo "GCP" ;;
    github) echo "GitHub" ;;
    k8s) echo "Kubernetes" ;;
    *) echo "$1" ;;
  esac
}

# The frontmatter description, rendered for a Markdown table cell. The agent
# parser accepts a quoted YAML scalar, so the source spelling is not always the
# value: strip a matched pair of surrounding quotes and undo that style's own
# escapes. Then escape the pipe, which would otherwise end the cell; the escape
# is valid Markdown anywhere in the cell, a code span included.
#
# A double-quoted scalar can carry escapes this does not decode (\x41, B), and
# a backslash surviving into the value has no single correct rendering: Markdown
# consumes it as an escape in prose and keeps it literally inside a code span.
# Rather than emit a corrupted value the renderer fails and names the file, and
# the author rewrites that description. The agent parser rejects a control
# character in the value, so the escapes that produce one are not valid input to
# begin with.
description() {
  sed -n '/^description:/{s/^description:[[:space:]]*//;p;q;}' "$1" |
    awk -v file="$1" -v sq="'" -v dq='"' '
      function fail(msg) {
        printf "error: %s: %s\n", file, msg > "/dev/stderr"
        exit 1
      }
      function unquote_double(s,   out, i, c, len) {
        len = length(s)
        for (i = 1; i <= len; i++) {
          c = substr(s, i, 1)
          if (c != "\\") { out = out c; continue }
          if (i == len) fail("description ends in a backslash")
          i++
          c = substr(s, i, 1)
          if (c != dq && c != "\\") {
            fail("description carries the escape \\" c ", which this renderer does not decode; write it plain or single-quoted")
          }
          out = out c
        }
        return out
      }
      function escape_pipe(s,   out, i, c) {
        for (i = 1; i <= length(s); i++) {
          c = substr(s, i, 1)
          if (c == "|") out = out "\\"
          out = out c
        }
        return out
      }
      {
        v = $0
        sub(/[ \t]+$/, "", v)
        n = length(v)
        if (n >= 2 && substr(v, 1, 1) == dq && substr(v, n, 1) == dq) {
          v = unquote_double(substr(v, 2, n - 2))
        } else if (n >= 2 && substr(v, 1, 1) == sq && substr(v, n, 1) == sq) {
          v = substr(v, 2, n - 2)
          gsub(sq sq, sq, v)
        }
        if (index(v, "\\") > 0) {
          fail("description carries a backslash, which Markdown renders differently in prose and in a code span; rewrite it without one")
        }
        print escape_pipe(v)
      }
    '
}

# Number of arguments; called with a glob so the shell, not ls, does the counting.
count() {
  echo "$#"
}

bt='`'
total=$(count agents/*.md)

{
  echo "# Built-in agent catalog"
  echo
  echo "<!-- Generated by scripts/docs/agents-catalog.sh from agents/*.md. Do not edit by hand. -->"
  echo
  echo "Cynative ships with $total built-in agents. Run one with"
  echo "${bt}cynative -p --agent <name>${bt}, print it with ${bt}cynative agents show <name>${bt},"
  echo "and see [agents.md](agents.md) for how to write your own."
  echo

  prev=""
  for f in agents/*.md; do
    name=$(basename "$f" .md)
    group=${name%%-*}
    if [ "$group" != "$prev" ]; then
      [ -n "$prev" ] && echo
      n=$(count agents/"$group"-*.md)
      echo "## $(group_title "$group") ($n)"
      echo
      echo "| Agent | What it answers |"
      echo "|---|---|"
      prev=$group
    fi
    desc=$(description "$f") || exit 1
    printf '| %s%s%s | %s |\n' "$bt" "$name" "$bt" "$desc"
  done
} > "$tmp"

if [ "$mode" = "check" ]; then
  if ! cmp -s "$out" "$tmp"; then
    echo "error: $out is stale; run 'make generate' and commit the result" >&2
    diff -u "$out" "$tmp" >&2 || true
    exit 1
  fi
  echo "ok: $out is up to date ($total agents)"
else
  # mktemp creates the file 0600; restore the world-readable mode Git tracks so
  # make generate does not flip docs/agents-catalog.md to owner-only.
  chmod 0644 "$tmp"
  mv "$tmp" "$out"
  echo "wrote $out ($total agents)"
fi
